### PR TITLE
Switch to Go modules

### PR DESCRIPTION
**Pull request by abhinav**
This switches the library over to Go modules. This significantly
simplifies the Makefile.

We can also delete the old coverage shell script now that `./...` just
works.

As per https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module,
tool dependencies have been added to tools.go.

### CODE REVIEW

**Comment by abhinav** [comment]
> Since `multierr` depends on `atomic`, will removing the `glide.yaml` cause any issues with projects that use dep and depend on `multierr`?

Consumers that are still using dep or glide will likely fall back to
the default behavior of "most recent stable release." I'm okay with
holding off on this, at least until the next Go release.

**Comment by prashantv** [comment]
> Consumers that are still using dep or glide will likely fall back to
> the default behavior of "most recent stable release." I'm okay with
> holding off on this, at least until the next Go release.

If we can validate this behaviour, then I'm OK with landing this. We should also validate that if there's another dependency on multierr with version specified, that the lack of a constraint is "compatible" and doesn't cause dep failures.

**Comment by abhinav** [comment]
Looks like `glide` falls back to `master`:

```
$ cat glide.yaml
package: github.com/abhinav/example
import:
- package: go.uber.org/multierr
  version: gomod
$ glide cc && glide up
...
$ grep -A1 atomic glide.lock
- name: go.uber.org/atomic
  version: ef0d20d85b01f4708a8085bca571838bf59a3f77
```

But `dep` to the most recent release.

```
$ grep -C1 multierr Gopkg.toml
[[constraint]]
  name = "go.uber.org/multierr"
  branch = "gomod"
$ dep ensure
$ grep -A4 atomic Gopkg.lock
  name = "go.uber.org/atomic"
  packages = ["."]
  pruneopts = "UT"
  revision = "df976f2515e274675050de7b3f42545de80594fd"
  version = "v1.4.0"
```

---

To me `glide`s default `master` behavior feels like a deal-breaker for this change.

**Comment by prashantv** [comment]
> To me glides default master behavior feels like a deal-breaker for this change.

That's a shame.. If we switched development to a `dev` branch and treated `master` as last release, maybe it's OK?

**Comment by abhinav** [comment]
Rebased on master and added glide.yaml back to appease legacy ecosystem. We'll want to keep the constraints in the go.mod and glide.yaml synced.

**Pull request merged**
